In [1]:
%run D:\qtlab_replacement\init.py
%matplotlib qt4
import matplotlib.pyplot as plt
from instruments import *
import numpy as np
import sweep
from save_pkl import *

# Resonator tunability spectorscopy

In [2]:
from resonator_tools import circuit
import fitting
import imp
imp.reload(fitting)

<module 'fitting' from 'D:\\qtlab_replacement\\scripts\\fitting.py'>

In [3]:
current_src = Yokogawa_GS210(address='gs210')
pna = Agilent_N5242A('pna', address = 'PNA')
lo1 = Agilent_E8257D('lo1', address = 'PSG1')
#pxa = Agilent_N9030A('pxa', address = 'PXA')
awg_tek = Tektronix_AWG5014('awg_tek', address = 'TCPIP0::10.20.61.186::inst0::INSTR')
adc = Spectrum_M3i2132('adc')
# векторный анализатор в режим линейного свипа
pna.set_sweep_mode("LIN")

root: WARNING  Tektronix_AWG5014 : get all not yet fully functional


True

In [16]:
pna.set_xlim(2e9,10e9)
pna.set_nop(3000)


True

In [19]:
plt.plot(20*np.log(pna.get_tracedata()[0]))

c:\python36\lib\site-packages\matplotlib\backend_bases.py:2445: MatplotlibDeprecationWarning: Using default event loop until function specific to this GUI is implemented
  warnings.warn(str, mplDeprecation)


In [27]:
current_src.set_status(0)
awg_tek.stop()
awg_tek.set_output(0, channel=1)
awg_tek.set_offset(0, channel=1)

True

In [28]:
awg_tek.set_offset(0.5, channel=1)
awg_tek.set_output(1, channel=1)
awg_tek.run()

In [33]:
currents = np.linspace(-1e-4, 1e-4, 101)
current_src.set_status(1)
pna.set_startfreq(9e9)
pna.set_stopfreq(10e9)
pna.set_bandwidth(200)
pna.set_nop(501)
pna.set_power(-60)
sweep.sweep(pna, (currents, current_src.set_current, 'Coil current'), filename='Hivemind spectrum coil')

Started at:  May 24 2017 20:42:03


c:\python36\lib\site-packages\matplotlib\backend_bases.py:2445: MatplotlibDeprecationWarning: Using default event loop until function specific to this GUI is implemented
  warnings.warn(str, mplDeprecation)


Time left: 0 h 0 m 0.0 s,	parameter values: Coil current: 0.0001,	average cycle time:    3s	s		3s	
Elapsed time: 0 h 4 m 59.33 s


{'S-parameter': (('Coil current', 'Frequency'),
  (array([ -1.00000000e-04,  -9.80000000e-05,  -9.60000000e-05,
           -9.40000000e-05,  -9.20000000e-05,  -9.00000000e-05,
           -8.80000000e-05,  -8.60000000e-05,  -8.40000000e-05,
           -8.20000000e-05,  -8.00000000e-05,  -7.80000000e-05,
           -7.60000000e-05,  -7.40000000e-05,  -7.20000000e-05,
           -7.00000000e-05,  -6.80000000e-05,  -6.60000000e-05,
           -6.40000000e-05,  -6.20000000e-05,  -6.00000000e-05,
           -5.80000000e-05,  -5.60000000e-05,  -5.40000000e-05,
           -5.20000000e-05,  -5.00000000e-05,  -4.80000000e-05,
           -4.60000000e-05,  -4.40000000e-05,  -4.20000000e-05,
           -4.00000000e-05,  -3.80000000e-05,  -3.60000000e-05,
           -3.40000000e-05,  -3.20000000e-05,  -3.00000000e-05,
           -2.80000000e-05,  -2.60000000e-05,  -2.40000000e-05,
           -2.20000000e-05,  -2.00000000e-05,  -1.80000000e-05,
           -1.60000000e-05,  -1.40000000e-05,  -1.200000

In [4]:
def set_res_z_voltage(dc):
    if dc<-.5:
        dc=-.5
    if dc>.5:
        dc=.5
    waveform = np.zeros(awg_tek.get_nop())*dc
    awg_tek.set_offset(dc, channel=1)
    awg_tek.set_waveform(waveform, channel=1)
    awg_tek.run()

In [34]:
awg_tek.set_amplitude(1.5, channel=1)
voltages = np.linspace(-0.5, 0.5, 101)
pna.set_startfreq(9e9)
pna.set_stopfreq(10e9)
pna.set_bandwidth(200)
pna.set_nop(501)
pna.set_power(-60)
sweep.sweep(pna, (voltages, set_res_z_voltage, 'Control voltage'), filename='Hivemind spectrum res-z')

Started at:  May 24 2017 20:47:06


c:\python36\lib\site-packages\matplotlib\backend_bases.py:2445: MatplotlibDeprecationWarning: Using default event loop until function specific to this GUI is implemented
  warnings.warn(str, mplDeprecation)


Time left: 0 h 0 m 0.0 s,	parameter values: Control voltage:    0.5,	average cycle time:  5.4s			
Elapsed time: 0 h 9 m 0.76 s


{'S-parameter': (('Control voltage', 'Frequency'),
  (array([-0.5 , -0.49, -0.48, -0.47, -0.46, -0.45, -0.44, -0.43, -0.42,
          -0.41, -0.4 , -0.39, -0.38, -0.37, -0.36, -0.35, -0.34, -0.33,
          -0.32, -0.31, -0.3 , -0.29, -0.28, -0.27, -0.26, -0.25, -0.24,
          -0.23, -0.22, -0.21, -0.2 , -0.19, -0.18, -0.17, -0.16, -0.15,
          -0.14, -0.13, -0.12, -0.11, -0.1 , -0.09, -0.08, -0.07, -0.06,
          -0.05, -0.04, -0.03, -0.02, -0.01,  0.  ,  0.01,  0.02,  0.03,
           0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ,  0.11,  0.12,
           0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ,  0.21,
           0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ,
           0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,
           0.4 ,  0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,
           0.49,  0.5 ]),
   array([  9.00000000e+09,   9.00200000e+09,   9.00400000e+09,
            9.00600000e+09,   9.00800000e+09,   9.010000

In [35]:
set_res_z_voltage(0.)

### loading data for resonator frequency on coil current and fitting

In [5]:
filename = 'S-parameter Hivemind spectrum coil'
location = 'D:\\qtlab\\ReiData\\data\\2017-05-24\\20-42-03'
#location = 'D:\\qtlab\\ReiData\\data\\2017-05-24\\11-33-10'
data = load_pkl(filename, location=location)[1]

fitresults = fitting.dc_squid_fit_S21(data, noise_sigma=5)
L_res_coil = fitresults['fitresults']['L']
I0_coil = fitresults['fitresults']['I0']

D:\qtlab\ReiData\data\2017-05-24\20-42-03/S-parameter Hivemind spectrum coil.pkl


c:\python36\lib\site-packages\numpy\core\fromnumeric.py:2889: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
c:\python36\lib\site-packages\numpy\core\_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
D:\qtlab_replacement\scripts\fitting.py:126: RuntimeWarning: invalid value encountered in sqrt
  ft = lambda I,fp,I0,L,a,b: np.real(fp*(1+b)*(1/(1/np.sqrt((1-a)*np.abs(np.cos((I-I0)*L).astype(np.complex))+a)+b)))
c:\python36\lib\site-packages\scipy\optimize\minpack.py:779: OptimizeWarning: Covariance of the parameters could not be estimated
  category=OptimizeWarning)
c:\python36\lib\site-packages\scipy\optimize\minpack.py:427: RuntimeWarning: Number of calls to function has reached maxfev = 600.
  warnings.warn(errors[info][0], RuntimeWarning)
c:\python36\lib\site-packages\resonator_tools-0.1-py3.6.egg\resonator_tools\circlefit.py:103: RuntimeWarning: invalid value encountered in sqrt
c:\python36\lib\site-packages\r

In [6]:
plt.figure('fQl')
print(fitresults)
plt.scatter(fitresults['fit_fr'],fitresults['fit_Ql'], marker='o', linewidth=0, label='Ql')
plt.scatter(fitresults['fit_fr'],fitresults['fit_Qc'], marker='o', linewidth=0, label='Qc')
plt.scatter(fitresults['fit_fr'],fitresults['fit_Qi'], marker='o', linewidth=0, label='Qi')
plt.gca().set_yscale('log')
plt.xlabel('f, Hz')
plt.ylabel('Q')
plt.legend()
plt.ylim(1e1, 1e6)

{'fitresults': {'fp': 9448160959.6030712, 'I0': -1.0315285415173258e-05, 'L': 15977.13059686321, 'a': 0.35440912882079173, 'b': 9.6686366106973676}, 'evaluator': <function dc_squid_fit_S21.<locals>.<lambda> at 0x000000000AFCFA60>, 'fp_est': array([  9.56375000e+09,   9.51125000e+09,   9.44250000e+09,
         9.36250000e+09,   9.26000000e+09,   9.12125000e+09,
         8.96750000e+09,   8.78375000e+09,   8.51875000e+09,
         8.24750000e+09,   8.54375000e+09,   8.79250000e+09,
         8.99125000e+09,   9.13750000e+09,   9.26625000e+09,
         9.36125000e+09,   9.43750000e+09,   9.51250000e+09,
         9.56375000e+09,   9.61250000e+09,   9.64750000e+09,
         9.67625000e+09,   9.69375000e+09,   9.71000000e+09,
         9.71750000e+09,   9.72000000e+09,   9.71750000e+09,
         9.70875000e+09,   9.69125000e+09,   9.67125000e+09,
         9.64000000e+09,   9.60625000e+09,   9.55750000e+09,
         9.50250000e+09,   9.43125000e+09,   9.34500000e+09,
         9.23375000e+09,   

(10.0, 1000000.0)

In [7]:
filename = 'S-parameter Hivemind spectrum res-z'
location = 'D:\\qtlab\\ReiData\\data\\2017-05-24\\20-47-06'
data = load_pkl(filename, location=location)[1]

fitresults = fitting.dc_squid_fit_S21(data, noise_sigma=5)
L_res_z = fitresults['fitresults']['L']

D:\qtlab\ReiData\data\2017-05-24\20-47-06/S-parameter Hivemind spectrum res-z.pkl


c:\python36\lib\site-packages\numpy\core\fromnumeric.py:2889: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
c:\python36\lib\site-packages\numpy\core\_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
D:\qtlab_replacement\scripts\fitting.py:126: RuntimeWarning: invalid value encountered in sqrt
  ft = lambda I,fp,I0,L,a,b: np.real(fp*(1+b)*(1/(1/np.sqrt((1-a)*np.abs(np.cos((I-I0)*L).astype(np.complex))+a)+b)))
c:\python36\lib\site-packages\scipy\optimize\minpack.py:427: RuntimeWarning: Number of calls to function has reached maxfev = 600.
  warnings.warn(errors[info][0], RuntimeWarning)
c:\python36\lib\site-packages\resonator_tools-0.1-py3.6.egg\resonator_tools\circuit.py:132: RuntimeWarning: invalid value encountered in sqrt
c:\python36\lib\site-packages\resonator_tools-0.1-py3.6.egg\resonator_tools\circuit.py:137: RuntimeWarning: invalid value encountered in sqrt
c:\python36\lib\site-packages\scipy\optimize\minp

### getting resonance frequency dependence on coil current

In [50]:
plt.figure('S21')
plt.pcolormesh(data['S-parameter'][1][0], data['S-parameter'][1][1], np.abs(data['S-parameter'][2].T))
plt.plot(fitresults['fp_est_xpoints'], fitresults['fp_est'])
#plt.plot(fitresults['fp_est_xpoints'], fitresults['fp_est'])
plt.plot(data['S-parameter'][1][0], fitresults['evaluator'](data['S-parameter'][1][0]))
plt.ylim([np.min(data['S-parameter'][1][1]), np.max(data['S-parameter'][1][1])])
fitresults['fitresults']

D:\qtlab_replacement\scripts\fitting.py:125: RuntimeWarning: invalid value encountered in sqrt
  ft = lambda I,fp,I0,L,a,b: np.real(fp*(1+b)*(1/(1/np.sqrt((1-a)*np.abs(np.cos((I-I0)*L).astype(np.complex))+a)+b)))


{'I0': -0.32358758108292035,
 'L': 2.8544584239999415,
 'a': -0.11171427474883659,
 'b': 4.8703036587757254,
 'fp': 9722002636.158638}

In [8]:
LM = np.asarray([[L_res_z, L_res_coil]])
res_z_compensation = lambda I_coil: -2*np.pi*(((I_coil*LM[0,1]/(2*np.pi)+0.5)%1.)-0.5)/LM[0,0]*2.5
#res_z_compensation = lambda I_coil: np.pi*(((I_coil*LM[0,1]/(np.pi)+0.5)%1.)-0.5)/LM[0,0]
offset_coil_current = 0
def set_coil_current_compensated(current_value):
    set_res_z_voltage(res_z_compensation(current_value))
    current_src.set_current(current_value+offset_coil_current)
    F = current_value*LM[0,1]/(2*np.pi)
    Fc = res_z_compensation(current_value)*LM[0,0]/(2*np.pi)
    #print ('coil current: {0},\n res-z current: {1},\n fluxoid num: {2},\n compensation fluxoid num: {3}'.format(current_value, res_z_compensation(current_value), F, Fc))
    
currents = np.linspace(-0.3e-4, 0.3e-4, 31)
pna.set_startfreq(9.66e9)
pna.set_stopfreq(9.74e9)
pna.set_bandwidth(30)
pna.set_nop(41)
pna.set_power(-65)
sweep.sweep(pna, \
            (currents, set_coil_current_compensated, 'Resonator shift compensated coil current'), \
            filename='Hivemind spectrum res-z')

Started at:  May 25 2017 17:28:48


c:\python36\lib\site-packages\matplotlib\backend_bases.py:2445: MatplotlibDeprecationWarning: Using default event loop until function specific to this GUI is implemented
  warnings.warn(str, mplDeprecation)


First sweep...

KeyboardInterrupt: 

In [133]:
set_coil_current_compensated(0)

# Two-tone spectroscopy at 0 resonator control current

In [10]:
pna.set_xlim(9.723e9, 9.723e9)
pna.set_bandwidth(10)
pna.set_averages(1)
pna.set_nop(1)
pna.set_power(-60)
lo1.set_power(-10)
lo1.set_status(1)

ex_freqs = np.linspace(7.55e9, 7.6e9, 51)
currents = np.linspace(-3e-5, 3e-5, 61)
sweep.sweep(pna, (currents, set_coil_current_compensated, 'Qubit control 1 current'),\
                 (ex_freqs, lo1.set_frequency, 'Excitation frequency'),\
                filename='Hivemind 2T spectrum Q1')

Started at:  May 25 2017 18:54:05


c:\python36\lib\site-packages\matplotlib\backend_bases.py:2445: MatplotlibDeprecationWarning: Using default event loop until function specific to this GUI is implemented
  warnings.warn(str, mplDeprecation)


Time left: 0 h 8 m 3.37 s,	parameter values: Qubit control 1 current: 1.5e-05,	Excitation frequency: 7.578e+09,	average cycle time: 0.61s				s	

KeyboardInterrupt: 

Time left: 0 h 7 m 15.08 s,	parameter values: Qubit control 1 current: 1.7e-05,	Excitation frequency: 7.558e+09,	average cycle time: 0.62s	

KeyboardInterrupt: 

In [15]:
pna.set_xlim(9.723e9, 9.723e9)
pna.set_bandwidth(2)
pna.set_averages(1)
pna.set_nop(1)
pna.set_power(-60)
lo1.set_power(-10)
lo1.set_status(1)
ex_powers = np.linspace(-20,-5, 31)

#ex_freqs = np.linspace(6e9, 8e9, 201)
ex_freqs = np.linspace(7.00e9, 7.750e9, 251)
set_coil_current_compensated(0)
sweep.sweep(pna, (ex_powers, lo1.set_power, 'Excitation power'),\
                 (ex_freqs, lo1.set_frequency, 'Excitation frequency'),\
                filename='Hivemind 2T power sweep')

Started at:  May 26 2017 09:47:17


c:\python36\lib\site-packages\matplotlib\backend_bases.py:2445: MatplotlibDeprecationWarning: Using default event loop until function specific to this GUI is implemented
  warnings.warn(str, mplDeprecation)


Time left: 0 h 0 m 0.0 s,	parameter values: Excitation power:     -5,	Excitation frequency: 7.75e+09,	average cycle time: 0.92s	s			
Elapsed time: 1 h 59 m 31.68 s


{'S-parameter': (('Excitation power', 'Excitation frequency'),
  (array([-20. , -19.5, -19. , -18.5, -18. , -17.5, -17. , -16.5, -16. ,
          -15.5, -15. , -14.5, -14. , -13.5, -13. , -12.5, -12. , -11.5,
          -11. , -10.5, -10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,
           -6.5,  -6. ,  -5.5,  -5. ]),
   array([  7.00000000e+09,   7.00300000e+09,   7.00600000e+09,
            7.00900000e+09,   7.01200000e+09,   7.01500000e+09,
            7.01800000e+09,   7.02100000e+09,   7.02400000e+09,
            7.02700000e+09,   7.03000000e+09,   7.03300000e+09,
            7.03600000e+09,   7.03900000e+09,   7.04200000e+09,
            7.04500000e+09,   7.04800000e+09,   7.05100000e+09,
            7.05400000e+09,   7.05700000e+09,   7.06000000e+09,
            7.06300000e+09,   7.06600000e+09,   7.06900000e+09,
            7.07200000e+09,   7.07500000e+09,   7.07800000e+09,
            7.08100000e+09,   7.08400000e+09,   7.08700000e+09,
            7.09000000e+09,   7.093000

In [19]:
pna.set_xlim(9.723e9, 9.723e9)
pna.set_bandwidth(1)
pna.set_averages(1)
pna.set_nop(1)
pna.set_power(-60)
lo1.set_power(-15)
lo1.set_status(1)

#ex_freqs = np.linspace(6e9, 8e9, 201)
ex_freqs = np.linspace(7.00e9, 7.750e9, 751)
set_coil_current_compensated(0)
sweep.sweep(pna, (ex_freqs, lo1.set_frequency, 'Excitation frequency'),\
                filename='Hivemind 2T power sweep')

Started at:  May 26 2017 19:37:21
First sweep...

c:\python36\lib\site-packages\matplotlib\backend_bases.py:2445: MatplotlibDeprecationWarning: Using default event loop until function specific to this GUI is implemented
  warnings.warn(str, mplDeprecation)


Time left: 0 h 0 m 0.0 s,	parameter values: Excitation frequency: 7.75e+09,	average cycle time:  1.2s	s			
Elapsed time: 0 h 15 m 24.45 s


{'S-parameter': (('Excitation frequency',),
  (array([  7.00000000e+09,   7.00100000e+09,   7.00200000e+09,
            7.00300000e+09,   7.00400000e+09,   7.00500000e+09,
            7.00600000e+09,   7.00700000e+09,   7.00800000e+09,
            7.00900000e+09,   7.01000000e+09,   7.01100000e+09,
            7.01200000e+09,   7.01300000e+09,   7.01400000e+09,
            7.01500000e+09,   7.01600000e+09,   7.01700000e+09,
            7.01800000e+09,   7.01900000e+09,   7.02000000e+09,
            7.02100000e+09,   7.02200000e+09,   7.02300000e+09,
            7.02400000e+09,   7.02500000e+09,   7.02600000e+09,
            7.02700000e+09,   7.02800000e+09,   7.02900000e+09,
            7.03000000e+09,   7.03100000e+09,   7.03200000e+09,
            7.03300000e+09,   7.03400000e+09,   7.03500000e+09,
            7.03600000e+09,   7.03700000e+09,   7.03800000e+09,
            7.03900000e+09,   7.04000000e+09,   7.04100000e+09,
            7.04200000e+09,   7.04300000e+09,   7.04400000e+